<script setup lang="ts">
import { ref } from 'vue'
import { useInView, motion } from 'motion-v'
import { useFlyIn } from './animate'

const scope = ref(null)
const isInView = useInView(scope, {
    once: true,
    margin: '0px 0px -50% 0px'
})
const flyIn = useFlyIn(isInView)
</script>

<template>
    <article id="own-doc" ref="scope">
        <header
            class="flex flex-col md:flex-row justify-between md:items-end w-full fern-gap"
        >
            <h2
                class="flex flex-col gap-2 text-2xl mb-2 text-gray-500 dark:text-gray-400 font-medium"
            >
                <motion.span v-bind="flyIn()"
                    >Your own documentation</motion.span
                >
                <motion.span
                    v-bind="flyIn(0.1)"
                    class="text-7xl font-semibold text-gradient from-violet-400 to-blue-500 z-10"
                >
                    in 1 line
                </motion.span>
            </h2>
            <div
                class="flex flex-col gap-2 max-w-md md:text-base md:pr-4 dark:font-medium"
            >
                <motion.p v-bind="flyIn(0.2)">It's not magic</motion.p>
                <motion.p v-bind="flyIn(0.3)">
                    With deep integration with OpenAPI schema<br />
                    Elysia can generate Swagger documentation for your API out
                    of the box
                </motion.p>
            </div>
        </header>
        <div class="preview">
            <motion.img
                v-bind="flyIn(0.5)"
                loading="lazy"
                class="image"
                src="/assets/scalar-preview-light.webp"
                alt="Scalar documentation generated by Elysia using Elysia Swagger plugin"
            />
            <motion.div class="showcase" v-bind="flyIn(0.6)">
                <slot />
            </motion.div>
        </div>
    </article>
</template>

<style>
@reference "../../tailwind.css";

#own-doc {
    @apply relative flex flex-col max-w-5xl w-full mx-auto my-8;

    & > .preview {
        @apply relative mt-6 pb-12 w-full px-4 lg:px-0;

        & > .image {
            @apply rounded-xl border dark:border-gray-800 w-full sm:w-[97%] bg-gray-50 dark:bg-gray-700 object-cover;
            aspect-ratio: 16/9.5;
            box-shadow: 0 25px 40px rgba(0, 0, 0, 0.05);

            html.dark & {
                content: url('/assets/scalar-preview-dark.webp');
            }
        }

        & > .showcase {
            @apply sm:absolute mt-4 sm:mt-0 bottom-0 right-4 lg:right-0 bg-white/90 dark:bg-gray-800/90 backdrop-blur border dark:border-gray-700 rounded-xl sm:max-w-[25rem] w-full;
            box-shadow: 0 25px 40px rgba(0, 0, 0, 0.05);

            html.dark & {
                box-shadow: 0 25px 40px rgba(0, 0, 0, 0.325);
            }

            & > div {
                @apply !bg-transparent;

                & > pre {
                    @apply !p-3;
                }
            }
        }
    }
}
</style>
